[versions]
agp = "8.6.0"
coil = "2.6.0"
converterKotlinxSerialization = "2.11.0"
flipperNetworkPlugin = "0.262.0"
kotlin = "2.0.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.7.0"
kotlinxSerializationJson = "1.6.3"
lottie = "6.4.0"
material = "1.12.0"
shimmer = "0.5.0"
timber = "5.0.1"
lifecycleViewmodelKtx = "2.8.3"
lifecycleLivedataKtx = "2.8.3"
lifecycleCommon = "2.8.3"
lifecycleRuntimeKtx = "2.8.3"
fragmentKtx = "1.8.1"
kotlinxCoroutinesCore = "1.8.0"
kotlinxCoroutinesAndroid = "1.8.0"
converterMoshi = "2.9.0"
moshi = "1.13.0"
retrofit = "2.11.0"
loggingInterceptor = "4.10.0"
dokka = "1.9.20"
androidxJunit = "1.3.0"
espressoCoreVersion = "3.7.0"

[libraries]
androidxCoreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidxAppcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
flipperNetworkPlugin = { module = "com.facebook.flipper:flipper-network-plugin", version.ref = "flipperNetworkPlugin" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
lifecycleViewmodelKtx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
lifecycleLivedataKtx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycleCommon = { group = "androidx.lifecycle", name = "lifecycle-common", version.ref = "lifecycleCommon" }
lifecycleRuntimeKtx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
fragmentKtx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }
kotlinxCoroutinesCore = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinxCoroutinesAndroid = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
converterMoshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "converterMoshi" }
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
converterKotlinxSerialization= { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "converterKotlinxSerialization" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
loggingInterceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "loggingInterceptor" }
extJunit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
espressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCoreVersion" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
